intrinsics = [
	"byte Ultima8Engine::I_getAlertActive(void)",
	"int16 Item::I_getFrame(Item *)",
	"void Item::I_setFrame(Item *, frame)",
	"int16 Item::I_getMapArray(Item *)",
	"int16 Item::I_getStatus(Item *)",
	"void Item::I_orStatus(Item *, uint16 flags)",
	"int16 Intrinsic006(6 bytes)",
	"byte Item::I_getSOMETHING_07(Item *)",
	"byte Intrinsic008(MainActor *?)",
	"byte Item::I_getZ(Item *)",
	"void Item::I_destroy(Item *)",
	"int16 I_getSOMETHING_0B(MainActor *?)",
	"void Intrinsic00C(2 bytes)",
	"byte Intrinsic00D(6 bytes)",
	"int16 Intrinsic00E(8 bytes)",
	"void I_playFlic(void), int16 I_playFlic(Item *, char *name, int16 sizex, int16 sizey)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Intrinsic011(4 bytes)",
	"void Intrinsic012(2 bytes)",
	"int16 Item::I_getX(Item *)",
	"int16 Item::I_getY(Item *)",
	"void AudioProcess::I_playSFXCru(Item *, uint16 sfxnum)",
	"int16 Item::I_getShape(Item *)",
	"void Intrinsic017(8 bytes)",
	"int16 UCMachine::I_rndRange(uint16 x, uint16 y)",
	"byte Item::I_legalCreateAtCoords(Item *, int16 shapeno, int16 frame, int16 x, int16 y, int16 z)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic01B(void)",
	"byte Intrinsic01C(4 bytes)",
	"int16 Intrinsic01D(4 bytes)",
	"int16 Intrinsic01E(16 bytes)",
	"byte Item::I_create(Item *, uint16 shapenum, uint16 framenum)",
	"void Item::I_popToCoords(Item *, uint16 x, uint16 y, uint16 z)",
	"void Intrinsic021(4 bytes)",
	"void Intrinsic022(Item *)",
	"int16 Intrinsic023(void)",
	"void Item::I_setShape(Item *, int16 shapeno)",
	"void Intrinsic025(4 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"int16 Intrinsic027(14 bytes)",
	"int16 Intrinsic028(12 bytes)",
	"int16 Intrinsic029(void)",
	"void AudioProcess::I_playAmbientSFXCru(Item *, sndno)",
	"int16 Item::I_getQLo(Item *)",
	"byte Intrinsic02C(4 bytes)",
	"void Item::I_setQHi(Item *, uint16 qhi_2d)",
	"byte Intrinsic02E(Item *, 8 bytes)",
	"byte Intrinsic02F(10 bytes)",
	"void Intrinsic030(4 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Intrinsic032(12 bytes)",
	"byte Intrinsic033(4 bytes)",
	"int16 Intrinsic034(8 bytes)",
	"byte Intrinsic035(4 bytes)",
	"int16 Intrinsic036(12 bytes)",
	"byte Intrinsic037(4 bytes)",
	"void Intrinsic038(Item *, int16)",
	"byte Intrinsic039(4 bytes)",
	"byte Intrinsic03A(Item *, int16 unk)",
	"void Item::I_setQLo(Item *, int16 qlo)",
	"int16 Intrinsic03C(4 bytes)",
	"void Intrinsic03D(4 bytes)",
	"void Intrinsic03E(4 bytes)",
	"int16 Intrinsic03F(4 bytes)",
	"void Intrinsic040(8 bytes)",
	"void Intrinsic041(2 bytes)",
	"byte Intrinsic042(6 bytes)",
	"void Intrinsic043(6 bytes)",
	"byte Intrinsic044(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic046(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic048(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic04A(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic04C(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic04E(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"int16 Intrinsic050(4 bytes)",
	"void Intrinsic051(4 bytes)",
	"void Intrinsic052(6 bytes)",
	"void Intrinsic053(6 bytes)",
	"void Intrinsic054(6 bytes)",
	"void Intrinsic055(6 bytes)",
	"void Intrinsic056(2 bytes)",
	"int16 Item::I_getSOMETHING_57(Item *)",
	"byte Item::I_doSOMETHING_58(Item *, uint16 unk)",
	"void Item::I_setFrame(Item *, frame)",
	"int16 Intrinsic05A(4 bytes)",
	"byte Item::I_legalCreateAtPoint(Item *, int16 shape, int16 frame, Item *)",
	"void Intrinsic05C(8 bytes)",
	"void Intrinsic05D(void)",
	"int16 Intrinsic05E(uint32, char *, int16 a, int16 b)",
	"void Intrinsic05F(void)",
	"void Intrinsic060(4 bytes)",
	"void Intrinsic061(8 bytes)",
	"void Intrinsic062(void)",
	"void Intrinsic063(12 bytes)",
	"void Intrinsic064(16 bytes)",
	"byte Intrinsic065(4 bytes)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_setSomething068(Item *, uint16 qlow)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Intrinsic06A(10 bytes)",
	"int16 Intrinsic06B(void)",
	"void Intrinsic06C(sometimes Item *)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte Intrinsic06F(6 bytes)",
	"byte Intrinsic070(void)",
	"void Intrinsic071(void)",
	"void Intrinsic072(void)",
	"void Intrinsic073(4 bytes)",
	"void Intrinsic074(void)",
	"void Intrinsic075(void)",
	"void Intrinsic076(4 bytes)",
	"int16 Intrinsic077(void)",
	"void Intrinsic078(void)",
	"int16 Intrinsic079(6 bytes)",
	"int16 Intrinsic07A(void)",
	"void Intrinsic07B(4 bytes)",
	"int16 Intrinsic07C(4 bytes)",
	"void Intrinsic07D(6 bytes)",
	"int16 Intrinsic07E(Item *)",
	"void Intrinsic07F(6 bytes)",
	"int16 Intrinsic080(4 bytes)",
	"int16 Intrinsic081(4 bytes)",
	"int16 Intrinsic082(4 bytes)",
	"void Intrinsic083(6 bytes)",
	"int16 Item::I_getQLo(Item *)",
	"void Intrinsic085(4 bytes)",
	"int16 Intrinsic086(void)",
	"int16 Intrinsic087(void)",
	"void Item::I_setSomething088(Item *, uint16 qhi_88)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Intrinsic08A(12 bytes)",
	"int16 Intrinsic08B(4 bytes)",
	"void Intrinsic08C(4 bytes)",
	"int16 Intrinsic08D(12 bytes)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Intrinsic08F(void)",
	"void Intrinsic090(void)",
	"void Intrinsic091(void)",
	"void Intrinsic092(void)",
	"void Intrinsic093(void)",
	"UNUSEDInt0094()",
	"byte Intrinsic095(void)",
	"int16 Intrinsic096(4 bytes)",
	"void Intrinsic097(void)",
	"void Intrinsic098(void)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Intrinsic09A(void)",
	"int16 Intrinsic09B(2 bytes)",
	"int16 Intrinsic09C(4 bytes)",
	"int16 Intrinsic09D(2 bytes)",
	"int16 Intrinsic09E(4 bytes)",
	"int16 Intrinsic09F(10 bytes)",
	"void Intrinsic0A0(4 bytes)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Intrinsic0A2(4 bytes)",
	"void Intrinsic0A3(6 bytes)",
	"byte Intrinsic0A4(6 bytes)",
	"byte Intrinsic0A5(6 bytes)",
	"int16 Intrinsic0A6(void)",
	"int16 Intrinsic0A7(4 bytes)",
	"void Intrinsic0A8(4 bytes)",
	"void Intrinsic0A9(void)",
	"void Intrinsic0AA(2 bytes)",
	"byte Intrinsic0AB(4 bytes)",
	"int16 Intrinsic0AC(2 bytes)",
	"int16 Item::I_getNpcNum(Item *)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Item::I_getQHi(Item *)",
	"int16 Intrinsic0B0(6 bytes)",
	"int16 Intrinsic0B1(6 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int32 I_getCurrentTimerTick(void)",
	"void Intrinsic0B4(void)",
	"int16 Intrinsic0B5(6 bytes)",
	"void Intrinsic0B6(void)",
	"int16 Intrinsic0B7(void)",
	"byte Intrinsic0B8(4 bytes)",
	"int16 Intrinsic0B9(4 bytes)",
	"void Intrinsic0BA(6 bytes)",
	"byte Intrinsic0BB(8 bytes)",
	"byte Intrinsic0BC(6 bytes)",
	"int16 Intrinsic0BD(12 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic0C0(12 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic0C2(12 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic0C4(2 bytes)",
	"byte Intrinsic0C5(6 bytes)",
	"void Intrinsic0C6(14 bytes)",
	"byte Intrinsic0C7(6 bytes)",
	"int16 Intrinsic0C8(12 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic0CA(6 bytes)",
	"void Intrinsic0CB(2 bytes)",
	"byte Intrinsic0CC(4 bytes)",
	"void Intrinsic0CD(6 bytes)",
	"int16 Intrinsic0CE(void)",
	"void Intrinsic0CF(6 bytes)",
	"int16 Intrinsic0D0(4 bytes)",
	"UNUSEDInt00D1()",
	"void Intrinsic0D2(void)",
	"UNUSEDInt00D3()",
	"void Intrinsic0D4(2 bytes)",
	"int16 Intrinsic0D5(4 bytes)",
	"byte Intrinsic0D6(void)",
	"int16 Intrinsic0D7(4 bytes)",
	"void Intrinsic0D8(4 bytes)",
	"int16 Item::I_getQLo(Item *)",
	"void Intrinsic0DA(void)",
	"void Intrinsic0DB(6 bytes)",
	"byte Intrinsic0DC(6 bytes)",
	"int16 Intrinsic0DD(4 bytes)",
	"void Intrinsic0DE(6 bytes)",
	"int16 Intrinsic0DF(6 bytes)",
	"void Intrinsic0E0(8 bytes)",
	"int16 Intrinsic0E1(4 bytes)",
	"int16 Intrinsic0E2(4 bytes)",
	"int16 Intrinsic0E3(4 bytes)",
	"int16 Intrinsic0E4(4 bytes)",
	"void Intrinsic0E5(6 bytes)",
	"void Intrinsic0E6(6 bytes)",
	"void Intrinsic0E7(4 bytes)",
	"int16 Intrinsic0E8(6 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Intrinsic0EB(void)",
	"void Intrinsic0EC(6 bytes)",
	"void Intrinsic0ED(6 bytes)",
	"void Intrinsic0EE(void)",
	"int16 Intrinsic0EF(4 bytes not Item *)",
	"int16 Item::I_getQHi(Item *)",
	"byte Intrinsic0F1(6 bytes)",
	"void Intrinsic0F2(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"int16 Item::I_getSOMETHING_F4(Item *)",
	"void Item::I_setSOMETHING_F5(Item *, uint16 unk)",
	"void Intrinsic0F6(void)",
	"int16 Intrinsic0F7(12 bytes)",
	"int16 Item::I_getNpcNum(Item *)",
	"int16 Intrinsic0F9(12 bytes)",
	"byte Intrinsic0FA(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte Intrinsic0FD(2 bytes)",
	"void Intrinsic0FE(4 bytes)",
	"int16 UCMachine::I_numToStr(int16 num)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"byte Intrinsic103(uint16 shapenum)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"byte Intrinsic112(4 bytes)",
	"int16 UCMachine::I_numToStr(int16 num)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"byte Intrinsic116(14 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic118(12 bytes)",
	"void Intrinsic119(4 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte Intrinsic11B(6 bytes)",
	"int16 Item::I_getNpcNum(Item *)",
	"int16 Intrinsic11D(12 bytes)",
	"int16 Intrinsic11E(4 bytes)",
	"byte Intrinsic11F(4 bytes)",
	"int16 Intrinsic120(4 bytes)",
	"byte Intrinsic121(4 bytes)",
	"byte Intrinsic122(4 bytes)",
	"int16 Item::I_getNpcNum(Item *)",
	"int16 Intrinsic124(4 bytes)",
	"void Intrinsic125(6 bytes)",
	"int16 UCMachine::I_numToStr(int16 num)",
	"byte Intrinsic127(8 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Intrinsic12A(4 bytes)",
	"int16 Intrinsic12B(4 bytes)",
	"byte Intrinsic12C(6 bytes)",
	"void Intrinsic12D(16 bytes)",
	"byte Intrinsic12E(4 bytes)",
	"int16 Intrinsic12F(Item *, uint16 unk)",
	"void Intrinsic130(4 bytes)",
	"void Intrinsic131(6 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getQHi(Item *)",
	"void Intrinsic134(2 bytes)",
	"void UNUSEDInt135(4 bytes)",
	"void UNUSEDInt136()",
	"void UNUSEDInt137()",
]
