intrinsics = [
	
	"byte Ultima8Engine::I_getAlertActive(void)",
	"int16 Item::I_getFrame(Item *)",
	"void Item::I_setFrame(Item *, frame)",
	"int16 Item::I_getMapArray(Item *)",
	"int16 Item::I_getStatus(Item *)",
	"void Item::I_orStatus(Item *, uint16 flags)",
	"int16 Intrinsic006(6 bytes)",
	"byte Item::I_getSOMETHING_07(Item *)",
	"byte Actor::I_isNPC(Item *)",
	"byte Item::I_getZ(Item *)",
	"void Item::I_destroy(Item *)",
	"int16 I_GetNPCDataField0x63_00B(Actor *)",
	"void I_NPCsetSomething_00C(int)",
	"byte Item::I_getDirToItem(Item *, itemno)",
	"int16 I_NPCSomething00E(Actor *, int, int)",
	"void I_playFlic(void), int16 I_playFlic(Item *, char *name, int16 sizex, int16 sizey)",
	
	"int16 Item::I_getQLo(Item *)",
	"int16 Actor::I_getMap(4 bytes)",
	"void Intrinsic012(2 bytes)",
	"int16 Item::I_getX(Item *)",
	"int16 Item::I_getY(Item *)",
	"void AudioProcess::I_playSFXCru(Item *, uint16 sfxnum)",
	"int16 Item::I_getShape(Item *)",
	"void Intrinsic017(8 bytes)",
	"int16 UCMachine::I_rndRange(uint16 x, uint16 y)",
	"byte Item::I_legalCreateAtCoords(Item *, int16 shapeno, int16 frame, int16 x, int16 y, int16 z)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic01B(void)",
	"byte Actor::I_getDir(4 bytes)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"int16 Intrinsic01E(16 bytes)",
	"byte Item::I_create(Item *, uint16 shapenum, uint16 framenum)",
	
	"void Item::I_popToCoords(Item *, uint16 x, uint16 y, uint16 z)",
	"void Actor::I_setDead(4 bytes)",
	"void I_push(Item *)",
	"int16 Intrinsic023(void)",
	"void Item::I_setShape(Item *, int16 shapeno)",
	"void Item::I_touch(Item *)",
	"int16 Item::I_getQHi(Item *)",
	"int16 I_getDirectionSomething(x1, y1, x2, y2, numdirs, aa, bb)", 
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 I_GetGlobal7e2d_029(void)",
	"void AudioProcess::I_playAmbientSFXCru(Item *, sndno)",
	"int16 Item::I_getQLo(Item *)",
	"byte Item::I_inFastArea(Item *)",
	"void Item::I_setQHi(Item *, uint16 qhi)",
	"byte I_legalMoveToPoint(Item *, Point *, int16 force)",
	"byte Intrinsic02F(10 bytes)",
	
	"void Item::I_pop(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Intrinsic032(12 bytes)",
	"byte Actor::I_isBusy(4 bytes)",
	"int16 Actor::I_getDir16(x1, y1, x2, y2)",
	"byte Actor::I_getSomeFlagMaybeCrouch(Item *)",
	"int16 Actor::I_doAnim(12 bytes)",
	"byte Intrinsic037(4 bytes)",
	"void AudioProcess::Intrinsic038(Item *, int16 sndno)",
	"byte Actor::I_isDead(Item *)",
	"byte AudioProcess::Intrinsic03A(Item *, int16 unk)",
	"void Item::I_setQLo(Item *, int16 qlo)",
	"int16 Item::I_getItemFamily(Item *)",
	"void Container::I_destroyContents(Item *)",
	"void Item::I_fallProbably(Item *)",
	"int16 Egg::I_getEggId(Item *)",
	
	"void CameraProcess::I_move_to(x, y, z)",
	"void CameraProcess::I_setCenterOn(objid)",
	"byte Intrinsic042(6 bytes)",
	"void AudioProcess::Intrinsic043(Item *, soundno)",
	"byte Item::I_IsOn(Item *, uint16 itemno)",
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_IsOn(Item *, uint16 itemno))",
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_IsOn(Item *, uint16 itemno)",
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_IsOn(Item *, uint16 itemno)",
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_IsOn(Item *, uint16 itemno)",
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_IsOn(Item *, uint16 itemno)",
	"int16 Item::I_getQHi(Item *)",
	
	"int16 I_GetNPCDataField0x2_050(Actor *)",
	"void I_NPCSomething_051(Actor *)",
	"void Intrinsic052(6 bytes)",
	"void I_SetNPCDataField0x8_053(Actor *, int)",
	"void I_SetNPCDataField0xA_054(Actor *, int)",
	"void I_NPCSetActivityProbably_055(Actor *, int)",
	"void Intrinsic056(2 bytes)",
	"int16 Item::I_getSOMETHING_57(Item *)",
	"byte Item::I_doSOMETHING_58(Item *, uint16 unk)",
	"void Item::I_setFrame(Item *, frame)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"byte Item::I_legalCreateAtPoint(Item *, int16 shape, int16 frame, Point *)",
	"void Item::I_getPoint(Item *, Point *)",
	"void Intrinsic05D(void)",
	"int16 I_playFlicsomething(uint32, char *, int16 a, int16 b)",
	"void Intrinsic05F(void)",
	
	"void Actor::I_setDead(4 bytes)",
	"void Actor::I_create(8 bytes)",
	"void Intrinsic062(void)",
	"void Actor::I_teleport(12 bytes)",
	"void Item::I_getFootpad(Item *, uint *, uint *, uint *)",
	"byte Item::I_isInNPC(Item *)",
	"int16 	Item::I_getQLo(Item *)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_setNpcNum(Item *, uint16 npcnum)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Item::I_move(Item *, int16 x, int16 y, uint16 z)",
	"int16 Intrinsic06B(void)",
	"void Intrinsic06C(sometimes Item *)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte Item::I_isCompletelyOn(Item *, uint16 other)",
	
	"byte Intrinsic070(void)",
	"void Intrinsic071(void)",
	"void Intrinsic072(void)",
	"void Actor::I_setDead(4 bytes)",
	"void Intrinsic074(void)",
	"void Intrinsic075(void)",
	"void AudioProcess::I_stopSFX(Item *)",
	"int16 Intrinsic077_Fade(void)",
	"void Intrinsic078(void)",
	"int16 MainActor::I_teleportToEgg(int, int, int)",
	"int16 Intrinsic07A_Fade(void)",
	"void Actor::I_clrImmortal(Actor *)",
	"int16 I_GetNPCDataField0_07C(Actor *)",
	"void I_NPCSetActivityProbably_07D(Actor *, int)",
	"int16 Item::I_getQuality(Item *)",
	"void Item::I_setQuality(Item *, int)",
	
	"int16 Item::I_use(Item *)",
	"int16 Intrinsic081(4 bytes)",
	"int16 I_GetNPCDataField0x57_082(Actor *)",
	"void I_SetNPCDataField0x57_083(Actor *, int)",
	"int16 Item::I_getQLo(Item *)",
	"void Actor::I_setImmortal(Actor *)",
	"int16 Intrinsic086(void)",
	"int16 Intrinsic087(void)",
	"void Item::I_setMapArray(Item *, uint16 maparray)",
	"int16 Item::I_getNpcNum(Item *)",
	"void Intrinsic08A(12 bytes)",
	"int16 Item::I_enterFastArea(Item *)",
	"void Item::I_DoSomethingAndSetStatusFlag0x8000(Item *)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Intrinsic08F_Fade(void)",
	
	"void Intrinsic090(void)",
	"void I_setSomeMovieGlobal(void)",
	"void I_playFlic092(char *)",
	"void I_clearSomeMovieGlobal(void)",
	"UNUSEDInt0094()",
	"byte Intrinsic095(void)",
	"int16 MainActor::I_teleportToEgg(int, int)",
	"void Intrinsic097(void)",
	"void I_ProcessDeathSilence_098(void)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"void Intrinsic09A_Fade(void)",
	"int16 Intrinsic09B_Fade(2 bytes)",
	"int16 Intrinsic09C_Fade(4 bytes)",
	"int16 Intrinsic09D_Fade(2 bytes)",
	"int16 Intrinsic09E_Fade(4 bytes)",
	"int16 Intrinsic09F_Fade(10 bytes)",
	
	"void I_SetItemFlag0x8000AndNPCField0x13Flag0_0A0(Actor *)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Item::I_getUnkEggType(Item *)",
	"void Egg::I_setEggXRange(Egg *, int)",
	"byte Item::I_overlaps(Item *, uint16 unk)",
	"byte Item::I_isOn(Item *, itemno)",
	"int16 Intrinsic0A6(void)",
	"int16 Egg::I_getEggXRange(Egg *)",
	"void Actor::I_setDead(Actor *)",
	"void I_playFlic0A9(char *)",
	"void I_playSFX(2 bytes)",
	"byte I_NPCGetField0x59Flag1_0AB(Actor *)",
	"int16 I_maybeGetFamilyOfType(2 bytes)",
	"int16 Item::I_getNPCNum(Item *)",
	"int16 Item::I_getQLo(Item *)",
	"int16 Item::I_getQHi(Item *)",
	
	"int16 Item::I_unequip(6 bytes)",
	"int16 Item::I_spawnUsecodeEvent0x13(Item *, 2 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int32 I_getCurrentTimerTick(void)",
	"void Intrinsic0B4(void)", 
	"int16 Item::I_equip(6 bytes)",
	"void Intrinsic0B6(void)", 
	"int16 I_GetNPCGlobal0x7e24_0B7(void)",
	"byte Intrinsic0B8(4 bytes)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"void Item::I_setQuality(Item *, int)",
	"byte Intrinsic0BB(8 bytes)",
	"byte Item::I_isOn(Item *, itemno)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	
	"int16 Item::I_hurl(Item *,8 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Intrinsic0C4(2 bytes)",
	"byte Item::I_isOn(Item *, itemno)",
	"void SpriteProcess::I_createSprite(word, word, word, word, uword, uword, ubyte)",
	"byte Item::I_getDirFromItem(Item *, itemno)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"byte I_NPCSomething_0CA(Actor *, int)",
	"void Intrinsic0CB(2 bytes)",
	"byte I_GetNPCDataField0x59Flag3_0CC(Actor *)",
	"void I_NPCSetActivityProbably_0CD(Actor *, int)",
	"int16 Intrinsic0CE(void)",
	"void Item::setQAndCallSomething(Item *, int16 q)",
	
	"int16 Item::I_use(Item *)",
	"UNUSEDInt00D1()",
	"void I_playFlic0D2(int *item,char *flicname,word sizex,word sizey)",
	"UNUSEDInt00D3()",
	"void I_playSFX(2 bytes)",
	"int16 Item::I_use(Item *)",
	"byte Intrinsic0D6(void)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"void Actor::I_setDead(4 bytes)",
	"int16 Item::I_getQLo(Item *)",
	"void Intrinsic0DA_Fade(void)",
	"void I_NPCSetActivityProbably_0DB(Actor *, int)",
	"byte Item::I_isOn(Item *, itemno)",
	"int16 I_GetNPCDataField0x4_0DD(Actor *)",
	"void I_SetNPCDataField0x5c_0DE(Actor *, int)",
	"int16 Actor::I_getEquip(6 bytes)",
	
	"void Actor::I_setEquip(8 bytes)",
	"int16 I_GetNPCDataField0x6_0E1(Actor *)",
	"int16 I_GetNPCDataField0x8_0E2(Actor *)",
	"int16 I_GetNPCDataField0xa_0E3(Actor *)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"void I_NPCSomething0E5(Actor *, uint16)",
	"void I_SetNPCDataField0x63_0E6(Actor *, int)",
	"void Actor::I_setDead(4 bytes)",
	"int16 Item::I_cast(6 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getQLo(Item *)",
	"int16 I_GetQOfAvatarInventoryItem0x4ed_0EB(void)",
	"void Item::I_popToEnd(Item*, int)",
	"void Item::I_popToContainer(Item*, int)", 
	"void Intrinsic0EE(void)",
	"int16 Intrinsic0EF(4 bytes not Item *)",
	
	"int16 Item::I_getQHi(Item *)",
	"byte Item::I_isOn(Item *, itemno)",
	"void I_NPCSetActivityProbably_0F2(Actor *, int)(6 bytes)",
	"int16 Item::I_getQHi(Item *)",
	"int16 Item::I_getQ(Item *)",
	"void Item::I_setQ(Item *, uint16 q)",
	"void Intrinsic0F6(void)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 Item::I_getNPCNum(Item *)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"byte Item::I_isOn(Item *, itemno)",
	"int16 Item::I_getQHi(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte I_SomethingAboutGlobal7e2f_0FD(int)",
	"void Intrinsic0FE(4 bytes)",
	"int16 UCMachine::I_numToStr(int16 num)",
	
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"byte Intrinsic103(uint16 shapenum)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"byte Actor::I_getDir(4 bytes)",
	"int16 UCMachine::I_numToStr(int16 num)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"byte Intrinsic116(14 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"void Item::I_DoSomethingAndSetStatusFlag0x8000(Item *)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"byte Item::I_getSomeFlag(Item *, uint16 unk)",
	"int16 Item::I_getNPCNum(Item *)",
	"int16 Item::I_hurl(Item *,8 bytes)",
	"int16 Intrinsic11E(Item *)",
	"byte Intrinsic11F(Item *)",
	
	"int16 Intrinsic120(Item *)",
	"byte Actor::I_getDir(4 bytes)",
	"byte Actor::I_isDead(Item *)",
	"int16 Item::I_getNPCNum(Item *)",
	"int16 Actor::I_getLastAnimSet(4 bytes)",
	"void Item::I_setQuality(Item *, int)",
	"int16 UCMachine::I_numToStr(int16 num)",
	"byte Item::I_getDirToCoords(Item *, uin16 x, uint16 y)",
	"void Item::I_andStatus(Item *, uint16 status)",
	"int16 Item::I_getNPCNum(Item *)",
	"void Item::I_DoSomethingAndSetStatusFlag0x8000(Item *)",
	"int16 Intrinsic12B(Item *)",
	"byte Item::I_isOn(Item *, itemno)",
	"void Item::I_getFootpadData(Item *, uint *, uint *, uint *)",
	"byte Actor::I_isDead(Item *)",
	"int16 Intrinsic12F(Item *, uint16 unk)",
	
	"void Actor::I_clrImmortal(Actor *)",
	"void I_NPCSetActivityProbably_131(Actor *, int)",
	"void Item::I_andStatus(Item *, int16 status)",
	"int16 Item::I_getQHi(Item *)",
	"void Intrinsic134(2 bytes)",
	"void Actor::I_setDead(Actor *)",
	"void UNUSEDInt136()",
	"void UNUSEDInt137()"
]
