intrinsics = [
	
	"byte World::I_getAlertActive(void)",
	"int16 Item::I_getFrame(Item *)",
	"void Item::I_setFrame(Item *, frame)",
	"int16 Item::I_getMapArray(Item *)", 
	"int16 Item::I_getStatus(Item *)",
	"void Item::I_orStatus(Item *, uint16 flags)",
	"int16 Item::I_equip(6 bytes)", 
	"byte Item::I_isOnScreen(Item *)", 
	"byte Actor::I_isNPC(Item *)", 
	"byte Item::I_getZ(Item *)",
	"void Item::I_destroy(Item *)", 
	"int16 Actor::I_GetNPCDataField0x63_00B(Actor *)", 
	"void Ultima8Engine::I_setAvatarInStasis(int)",
	"byte Item::I_getDirToItem(Item *, itemno)", 
	"int16 Actor::I_turnToward(Actor *, direction, unk)", 
	"void I_playFlic(void), int16 I_playFlic(Item *, char *name, int16 sizex, int16 sizey)",
	
	"int16 Item::I_getQLo(Item *)", 
	"int16 Actor::I_getMap(4 bytes)", 
	"void MusicProcess:I_playMusic(int trackno)",
	"int16 Item::I_getX(Item *)",
	"int16 Item::I_getY(Item *)",
	"void AudioProcess::I_playSFXCru(Item *, uint16 sfxnum)",
	"int16 Item::I_getShape(Item *)", 
	"void Item::I_explode(Item *, exptype, destroy_item)",
	"int16 UCMachine::I_rndRange(uint16 x, uint16 y)", 
	"byte Item::I_legalCreateAtCoords(Item *, int16 shapeno, int16 frame, int16 x, int16 y, int16 z)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 I_getTargetNPCNumMaybe(void)",
	"byte Actor::I_getDir(4 bytes)", 
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"int16 Actor::I_maybeFire(Actor *, x, y, z, byte, int, byte)", 
	"byte Item::I_create(Item *, uint16 shapenum, uint16 framenum)", 
	
	"void Item::I_popToCoords(Item *, uint16 x, uint16 y, uint16 z)", 
	"void Actor::I_setDead(4 bytes)", 
	"void I_push(Item *)", 
	"int16 Item::I_getEtherealTop(void)", 
	"void Item::I_setShape(Item *, int16 shapeno)", 
	"void Item::I_touch(Item *)", 
	"int16 Item::I_getQHi(Item *)", 
	"int16 I_getClosestDirectionInRange(x1, y1, x2, y2, numdirs, mindir, maxdir)",
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Game::I_getDifficultyLevel(void)",
	"void AudioProcess::I_playAmbientSFXCru(Item *, sndno)",
	"int16 Item::I_getQLo(Item *)", 
	"byte Item::I_inFastArea(Item *)",
	"void Item::I_setQHi(Item *, uint16 qhi)", 
	"byte I_legalMoveToPoint(Item *, Point *, int16 force)", 
	"byte Intrinsic02F(int, int, shapeno, Point *)", 
	
	"void Item::I_pop(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"void Item::I_receiveHit(Item *, other, dir, damage, damagetype)", 
	"byte Actor::I_isBusy(4 bytes)", 
	"int16 Item::I_getDirFromTo16(x1, y1, x2, y2)",
	"byte Actor::I_getSomeFlagProbablyCrouch(Item *)",
	"int16 Actor::I_doAnim(12 bytes)", 
	"byte MainActor::I_addItemCru(4 bytes)", 
	"void AudioProcess::I_stopSFXCru(Item *, int16 sndno)",
	"byte Actor::I_isDead(Item *)", 
	"byte AudioProcess::I_isSFXPlayingForObject(Item *, int16 unk)",
	"void Item::I_setQLo(Item *, int16 qlo)", 
	"int16 Item::I_getItemFamily(Item *)", 
	"void Container::I_destroyContents(Item *)",
	"void Item::I_fallProbably_03E(Item *)", 
	"int16 Egg::I_getEggId(Item *)", 
	
	"void CameraProcess::I_moveTo(x, y, z)",
	"void CameraProcess::I_setCenterOn(objid)",
	"byte Item::I_getRangeIfVisible(Item *, otheritem)",
	"void AudioProcess::I_playSFXCru(Item *, soundno)", 
	"byte Item::I_IsOn(Item *, uint16 itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_IsOn(Item *, uint16 itemno))", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_IsOn(Item *, uint16 itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_IsOn(Item *, uint16 itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_IsOn(Item *, uint16 itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_IsOn(Item *, uint16 itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	
	"int16 I_GetNPCDataField0x2_050(Actor *)",
	"void Actor::I_clrInCombat(Actor *)", 
	"void Actor::I_setDefaultActivity0(Actor *, int)",
	"void Actor::I_setDefaultActivity1(Actor *, int)",
	"void Actor::I_setDefaultActivity2(Actor *, int)",
	"void Actor::I_setActivity(Actor *, int)", 
	"void Intrinsic056(int itemno)", 
	"int16 Item::I_getSurfaceWeight(Item *)",
	"byte Item::I_isCentreOn(Item *, uint16 other)",
	"void Item::I_setFrame(Item *, frame)", 
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"byte Item::I_legalCreateAtPoint(Item *, int16 shape, int16 frame, Point *)", 
	"void Item::I_getPoint(Item *, Point *)",
	"void I_mouseSomethingOffMaybe05D(void)",
	"int16 I_playFlicsomething(uint32, char *, int16 a, int16 b)", 
	"void I_mouseSomethingResume05F(void)",
	
	"void Actor::I_setDead(4 bytes)", 
	"void Actor::I_create(8 bytes)",
	"void CameraProcess::I_somethingAboutCameraUpdate(void)",
	"void Actor::I_teleport(12 bytes)", 
	"void Item::I_getFootpad(Item *, uint *, uint *, uint *)", 
	"byte Item::I_isInNPC(Item *)", 
	"int16 Item::I_getQLo(Item *)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_setNpcNum(Item *, uint16 npcnum)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"void Item::I_move(Item *, int16 x, int16 y, uint16 z)",
	"int16 Game::I_isViolenceEnabled(void)",
	"void Kernel::I_resetRef(int16, int16)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"byte Item::I_isCompletelyOn(Item *, uint16 other)",
	
	"byte Ultima8Engine::I_getUnkCrusaderFlag(void)",
	"void Ultima8Engine::I_setUnkCrusaderFlag(void)",
	"void Ultima8Engine::I_setCruStasis(void)",
	"void Actor::I_setDead(4 bytes)", 
	"void Ultima8Engine::I_clrUnkCrusaderFlag(void)",
	"void Ultima8Engine::I_clrCruStasis(void)",
	"void AudioProcess::I_stopSFX(Item *)",
	"int16 PaletteFaderProcess::I_fadeToBlack(void)", 
	"void MainActor::I_clrKeycards(void)",
	"int16 MainActor::I_teleportToEgg(int, int, int)",
	"int16 PaletteFaderProcess::I_fadeFromBlack(void)", 
	"void Actor::I_clrImmortal(Actor *)", 
	"int16 Actor::I_getHp(Actor *)", 
	"void Actor::I_setActivity(Actor *, int)", 
	"int16 Item::I_getQuality(Item *)", 
	"void Item::I_setQuality(Item *, int)", 
	
	"int16 Item::I_use(Item *)", 
	"int16 MainActor::I_getMaxEnergy(Actor *)",
	"int16 Actor::I_getMana(Actor *)",
	"void Actor::I_setMana(Actor *, int)",
	"int16 Item::I_getQLo(Item *)", 
	"void Actor::I_setImmortal(Actor *)",
	"int16 CameraProcess::I_getCameraX(void)",
	"int16 CameraProcess::I_getCameraY(void)",
	"void Item::I_setMapArray(Item *, uint16 maparray)", 
	"int16 Item::I_getNpcNum(Item *)", 
	"void Intrinsic08A(12 bytes)", 
	"int16 Item::I_enterFastArea(Item *)", 
	"void Item::I_setIsBroken(Item *)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void PaletteFaderProcess::I_setPalToAllBlack(void)",
	
	"void MusicProcess::I_musicStop(void)",
	"void I_setSomeMovieGlobal(void)", 
	"void I_playFlic092(char *)", 
	"void I_clearSomeMovieGlobal(void)", 
	"void Game::I_playCredits(void)",
	"byte Kernel::I_getCurrentKeyDown(void)", 
	"int16 MainActor::I_teleportToEgg(int, int)", 
	"void PaletteFaderProcess:I_setScreenGreyscale(void)", 
	"void I_resetVargasHealthTo500(void)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"void PaletteFaderProcess::I_stopFadesAndResetToGamePal(void)", 
	"int16 PaletteFaderProcess::I_fadeFromBlack(nsteps)",
	"int16 PaletteFaderProcess::I_fadeFromBlackWithParam(nsteps, unk)", 
	"int16 PaletteFaderProcess::I_fadeToBlack(nsteps)",
	"int16 PaletteFaderProcess::I_fadeToBlackWithParam(nsteps, unk)", 
	"int16 PaletteFaderProcess::I_fadeToColor(r, g, b, nsteps, unk)", 
	
	"void Actor::I_setDead(Actor *)", 
	"int16 Item::I_getQLo(Item *)", 
	"int16 Item::I_getUnkEggType(Item *)", 
	"void Egg::I_setEggXRange(Egg *, int)", 
	"byte Item::I_overlaps(Item *, uint16 unk)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"int16 I_getAnimationsDisabled(void)", 
	"int16 Egg::I_getEggXRange(Egg *)", 
	"void Actor::I_setDead(Actor *)", 
	"void I_playFlic0A9(char *)", 
	"void I_playSFX(2 bytes)", 
	"byte Actor::I_NPCGetField0x59Flag1_0AB(Actor *)",
	"int16 Item::I_getFamilyOfType(Item *)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"int16 Item::I_getQLo(Item *)", 
	"int16 Item::I_getQHi(Item *)", 
	
	"int16 Item::I_unequip(6 bytes)",
	"int16 Item::I_spawnUsecodeEvent0x13(Item *, 2 bytes)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int32 I_getCurrentTimerTick(void)",
	"void Ultima8Engine::I_setAlertActive(void)",
	"int16 Item::I_equip(6 bytes)",
	"void Ultima8Engine::I_clrAlertActive(void)",
	"int16 Ultima8Engine::I_getAvatarInStasis(void)",
	"byte MainActor::I_addItemCru(4 bytes)", 
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"void Item::I_setQuality(Item *, int)", 
	"byte Intrinsic0BB(8 bytes)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Item::I_getQHi(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 KeypadGump::I_showKeypad(int targetCode)",
	"byte Item::I_isOn(Item *, itemno)", 
	"void SpriteProcess::I_createSprite(word, word, word, word, uword, uword, ubyte)",
	"byte Item::I_getDirFromItem(Item *, itemno)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Item::I_getQHi(Item *)", 
	"byte Actor::I_addHp(Actor *, int)",
	"void I_createMapJumpProcess(int16 mapnum)", 
	"byte Actor::I_getInCombat(Actor *)",
	"void Actor::I_setActivity(Actor *, int)", 
	"int16 Game::I_isReleaseBuild(void)", 
	"void Item::I_setQAndCombine(Item *, int16 q)", 
	
	"int16 Item::I_use(Item *)", 
	"void AudioProcess:I_stopAllSFX(void)", 
	"void I_playFlic0D2(int *item,char *flicname,word sizex,word sizey)", 
	"void Intrinsic0D3(void)", 
	"void I_playSFX(2 bytes)", 
	"int16 Item::I_use(Item *)", 
	"byte CameraProcess::I_getCameraZ(void)",
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"void Actor::I_setDead(4 bytes)", 
	"int16 Item::I_getQLo(Item *)", 
	"void PaletteFaderProcess::I_setPalToAllGrey(void)", 
	"void Actor::I_setActivity(Actor *, int)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"int16 Actor::I_GetNPCDataField0x4_0DD(Actor *)",
	"void Actor::I_setCombatTactic(Actor *, int)",
	"int16 Actor::I_getEquip(6 bytes)", 
	
	"void Actor::I_setEquip(8 bytes)",
	"int16 Actor::I_getDefaultActivity0(Actor *)",
	"int16 Actor::I_getDefaultActivity1(Actor *)",
	"int16 Actor::I_getDefaultActivity2(Actor *)",
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"void Actor::I_attack(Actor *, uint16 target)",
	"void Actor::I_SetNPCDataField0x63_0E6(Actor *, int)",
	"void Actor::I_setDead(4 bytes)", 
	"int16 Item::I_cast(6 bytes)",
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getQLo(Item *)", 
	"int16 I_GetQOfAvatarInventoryItem0x4ed_0EB(void)",
	"void Item::I_popToEnd(Item*, int)", 
	"void Item::I_popToContainer(Item*, int)",  
	"void BatteryChargerProcess::I_create(void)",
	"int16 Kernel::I_getNumProcesses(int, int)", 
	
	"int16 Item::I_getQHi(Item *)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"void Actor::I_setActivity(Actor *, int)", 
	"int16 Item::I_getQHi(Item *)", 
	"int16 Item::I_getQ(Item *)", 
	"void Item::I_setQ(Item *, uint16 q)", 
	"void CruHealer::I_create_0F6(void)",
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"int16 Item::I_getQHi(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"byte MainActor::I_hasKeycard(int)",
	"void ComputerGump::I_readComputer(char *)",
	"int16 UCMachine::I_numToStr(int16 num)", 
	
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"byte Item::I_isCrusTypeNPC(uint16 shapenum)",
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"byte Actor::I_getDir(Actor *)", 
	"int16 UCMachine::I_numToStr(int16 num)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"byte Intrinsic116(14 bytes)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"void Item::I_setIsBroken(Item *)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"byte Item::I_getTypeFlag(Item *, uint16 shift)",
	"int16 Item::I_getNPCNum(Item *)", 
	"int16 Item::I_hurl(Item *,8 bytes)", 
	"int16 Item::I_getCY(Item *)", 
	"byte Item::I_getCZ(Item *)", 
	
	"int16 Item::I_getCX(Item *)",
	"byte Actor::I_getDir(4 bytes)", 
	"byte Actor::I_isDead(Item *)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"int16 Actor::I_getLastAnimSet(4 bytes)", 
	"void Item::I_setQuality(Item *, int)", 
	"int16 UCMachine::I_numToStr(int16 num)", 
	"byte Item::I_getDirToCoords(Item *, uin16 x, uint16 y)", 
	"void Item::I_andStatus(Item *, uint16 status)", 
	"int16 Item::I_getNPCNum(Item *)", 
	"void Item::I_setIsBroken(Item *)", 
	"int16 IItem::I_getCY(Item *)", 
	"byte Item::I_isOn(Item *, itemno)", 
	"void Item::I_getFootpadData(Item *, uint *, uint *, uint *)", 
	"byte Actor::I_isDead(Item *)", 
	"int16 Actor::I_createActorCru(Item *, uint16 other_itemno)",
	
	"void Actor::I_clrImmortal(Actor *)", 
	"void Actor::I_setActivity(Actor *, int)", 
	"void Item::I_andStatus(Item *, int16 status)", 
	"int16 Item::I_getQHi(Item *)", 
	"void Intrinsic134(2 bytes)", 
	"void Actor::I_setDead(Actor *)", 
	"void UNUSEDInt136()",
	"void UNUSEDInt137()"
]
