intrinsics = [
	"process target()",
	"Item::getNext()",
	"Item::touch()",
	"word Item::getX()",
	"word Item::getY()",
	"word Item::getZ()",
	"word Item::getCX()",
	"word Item::getCY()",
	"word Item::getCZ()",
	"word Item::Ultima8::getGumpX()",
	"word Item::Ultima8::getGumpY()",
	"void Item::setGumpXY(word x, word y)",
	"Item::getPoint(WorldPoint*)",
	"uword Item::getType()",
	"void Item::setType(uword type)",
	"uword Item::getFrame()",

	"void Item::setFrame(uword frame)",
	"uword Item::getQuality()",
	"uword Item::getUnkEggType()",
	"uword Item::getQuantity()",
	"Item::getContents()",
	"Item::getContainer()",
	"Item::getRootContainer()",
	"uword Item::getGlobNum()",
	"void Item::setGlobNum(uword)",
	"uword Item::getQ()",
	"void Item::setQ(uword)",
	"void Item::setQuality(word value)",
	"void Item::setUnkEggType(word value)",
	"void Item::setQuantity(word value)",
	"word Item::getFamily()",
	"bool Item::getTypeFlag(word bit)",

	"word Item::getStatus()",
	"void Item::orStatus(word mask)",
	"void Item::andStatus(word mask)",
	"Item::getFootpad(word*, word*, word*)",
	"Item::touches(uword)",
	"Item::overlaps(uword)",
	"Item::overlapsXY(uword)",
	"Item::isOn(uword)",
	"Item::isCompletelyOn(uword)",
	"Item::isAbove(uword)",
	"Item::isUnder(uword)",
	"Item::ascend(word)",
	"Item::getWeight()",
	"Item::getWeightIncludingContents()",
	"Item::getSurfaceWeight()",
	"Item::getVolume()",

	"Item::getCapacity()",
	"Item::legal_create(uword, uword, uword, uword, uword)",
	"Item::create(uword, uword)",
	"Item::legal_create(uword, uword, WorldPoint*)",
	"Item::legal_create(uword, uword, uword, word)",
	"Item::push()",
	"Item::pop(uword, uword, ubyte)",
	"Item::pop(uword)",
	"Item::pop()",
	"Item::popToEnd(uword)",
	"Item::destroy()",
	"Item::removeContents()",
	"Item::destroyContents()",
	"Item::isExplosive()",
	"Item::move(uword, uword, ubyte)",
	"Item::move(WorldPoint*)",

	"Item::legal_move(WorldPoint*, uword, uword)",
	"Item::legal_move(uword*, uword)",
	"Item::isNpc()",
	"Item::isInNpc()",
	"process Item::hurl(word, word, word, word)",
	"Item::shoot(WorldPoint*, word, word)",
	"Item::fall()",
	"Item::grab()",
	"Item::findTarget(word, word)",
	"process Item::bark(char* str)",
	"strptr process Item::ask(uword slist)",
	"word Item::getSliderInput(word min, word max, word step)",
	"Item::openGump(word)",
	"Item::closeGump()",
	"Item::isGumpOpen()",
	"Item::getNpcArray()",

	"Item::getMapArray()",
	"Item::setNpcArray(word)",
	"Item::setMapArray(word)",
	"Item::receiveHit(uword, byte, word, uword)",
	"Item::explode()",
	"Item::canReach(uword, word)",
	"Item::getRange(uword)",
	"Item::getRange(uword, uword, uword)",
	"Item::getDirToCoords(uword, uword)",
	"Item::getDirFromCoords(uword, uword)",
	"Item::getDirToItem(uword)",
	"Item::getDirFromItem(uword)",
	"process Item::look()",
	"process Item::use()",
	"process Item::anim()",
	"process Item::cachein()",

	"Item::hit(uword, word)",
	"process Item::gotHit(uword, word)",
	"process Item::release()",
	"process Item::equip()",
	"process Item::unequip()",
	"process Item::combine()",
	"process Item::calledFromAnim()",
	"process Item::enterFastArea()",
	"process Item::leaveFastArea()",
	"process Item::cast(uword)",
	"process Item::justMoved()",
	"process Item::AvatarStoleSomething(uword)",
	"process Item::animGetHit(uword)",
	"process Item::guardianBark(word)",
	"process Book::read(char*)",
	"process Scroll::read(char*)",

	"process Grave::read(word,char*)",
	"process Plaque::read(word,char*)",
	"Egg::getEggXRange()",
	"Egg::getEggYRange()",
	"Egg::setEggXRange(uword)",
	"Egg::setEggYRange(uword)",
	"Egg::getEggId()",
	"Egg::setEggId(uword)",
	"Egg::hatch()",
	"MonsterEgg::hatch()",
	"MonsterEgg::getMonId()",
	"MonsterEgg::getActivity()",
	"MonsterEgg::getShapeType()",
	"MonsterEgg::setMonId(word)",
	"MonsterEgg::setActivity(word)",
	"MonsterEgg::setShapeType(word)",

	"Npc::isBusy()",
	"Npc::areEnemiesNear()",
	"Npc::isInCombat()",
	"Npc::setInCombat()",
	"Npc::clrInCombat()",
	"Npc::setTarget(uword)",
	"Npc::getTarget()",
	"Npc::setAlignment(ubyte)",
	"Npc::getAlignment()",
	"Npc::setEnemyAlignment(ubyte)",
	"Npc::getEnemyAlignment()",
	"Npc::isEnemy(uword)",
	"Npc::isDead()",
	"Npc::setDead()",
	"Npc::clrDead()",
	"Npc::isImmortal()",

	"Npc::setImmortal()",
	"Npc::clrImmortal()",
	"Npc::isWithstandDeath()",
	"Npc::setWithstandDeath()",
	"Npc::clrWithstandDeath()",
	"Npc::isFeignDeath()",
	"Npc::setFeignDeath()",
	"Npc::clrFeignDeath()",
	"Npc::freeEquip(uword)",
	"Npc::clearEquip()",
	"Npc::getNpcSlot()",
	"Npc::freeNpcSlot()",
	"Npc::getDir()",
	"Npc::getMap()",
	"Npc::teleport(uword, uword, ubyte, ubyte)",
	"process Npc::doAnim(AnimSet, word, word, ubyte)",

	"Npc::getLastAnimSet()",
	"process Npc::pathfind(uword, uword, uword, uword)",
	"process Npc::pathfind(uword, uword)",
	"byte Npc::getStr()",
	"byte Npc::getInt()",
	"byte Npc::getDex()",
	"ubyte Npc::getHp()",
	"word Npc::getMana()",
	"void Npc::setStr(byte str)",
	"void Npc::setInt(byte int)",
	"void Npc::setDex(byte dex)",
	"void Npc::setHp(ubyte hp)",
	"void Npc::setMana(word mana)",
	"Npc::create(uword, uword)",
	"process Npc::cSetActivity(Activity)",
	"Npc::setAirWalkEnabled(ubyte)",

	"Npc::getAirWalkEnabled()",
	"Npc::schedule(ulong)",
	"Npc::getEquip(word)",
	"Npc::setEquip(word, uword)",
	"closeAllGumps()",
	"process Camera::scrollTo(uword, uword, ubyte, word)",
	"urandom(word)",
	"rndRange(word,word)",
	"castGrantPeaceSpell()",
	"numToStr(uword)",
	"strToNum(char*)",
	"playMusic(byte)",
	"getName()",
	"igniteChaos(uword, uword, ubyte)",
	"Camera::setCenterOn(uword)",
	"Camera::move_to(uword, uword, ubyte, word)",

	"Camera::move_rel(word, word, word)",
	"Camera::set_roof(word)",
	"Camera::roof()",
	"Camera::getX()",
	"Camera::getY()",
	"Camera::getZ()",
	"Camera::startQuake(word)",
	"Camera::stopQuake()",
	"Camera::invertScreen(ubyte)",
	"U8MousePointer::getDir()",
	"Kernel::getNumProcesses(uword, ProcessType)",
	"Kernel::resetRef(uword, ProcessType)",
	"process teleportToEgg(word, word, ubyte)",
	"resetRef(uword, uword)",
	"setRef(uword, uword, uword)",
	"getAvatarInStasis()",

	"setAvatarInStasis(word)",
	"getEtherealTop()",
	"getCurrentTimerTick()",
	"canGetThere(uword, uword, uword)",
	"canExistAt(uword, uword, uword, uword, ubyte, uword, word)",
	"createSprite(word, word, word, word, word, word, uword, uword, ubyte)",
	"createSprite(word, word, word, word, uword, uword, ubyte)",
	"word getFamilyOfType(uword type)",
	"TimeInGameHours()",
	"TimeInMinutes()",
	"TimeInSeconds()",
	"SetTimeInGameHours(word)",
	"SetTimeInMinutes(long)",
	"SetTimeInSeconds(long)",
	"process FadeToBlack()",
	"process FadeFromBlack()",

	"process FadeToPalette(word, word)",
	"process LightningBolt()",
	"process FadeToWhite()",
	"process FadeFromWhite()",
	"playEndgame()",
	"FeedAvatar(word)",
	"AccumulateStrength(word)",
	"AccumulateIntelligence(word)",
	"AccumulateDexterity(word)",
	"ClrAvatarInCombat()",
	"SetAvatarInCombat()",
	"IsAvatarInCombat()",
	"playSFX(word)",
	"playSFX(word, ubyte)",
	"playSFX(word, word, uword)",
	"playAmbientSFX(word)",

	"playAmbientSFX(word, word)",
	"playAmbientSFX(word, word, uword)",
	"isSFXPlaying(word)",
	"setVolumeSFX(word, word)",
	"stopSFX(word)",
	"stopSFX(word, uword)",
	"soundInit(word, word, word)",
	"soundDeInit()",
	"musicStop()",
	"musicSlowStop()",
	"musicPlay(word)",
	"TonysBalls(word, word, uword, uword, uword)",
	"AvatarCanCheat()",
	"MakeAvatarACheater()",
	"isGameRunning()",
	"unused",

	"unused",
]
